version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MCP_DATABASE_HOST=postgres
      - MCP_DATABASE_PORT=5432
      - MCP_DATABASE_USERNAME=postgres
      - MCP_DATABASE_PASSWORD=postgres
      - MCP_DATABASE_DATABASE=mcp
      - MCP_CACHE_TYPE=redis
      - MCP_CACHE_ADDRESS=redis:6379
    volumes:
      - ./configs:/app/configs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mcp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries