apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server
  namespace: mcp
  annotations:
    # IRSA annotations for AWS IAM Role
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/mcp-server-role
    # Optional: session name annotation
    eks.amazonaws.com/sts-regional-endpoints: "true"
