# MCP Server Configuration Template

# Storage Configuration
storage:
  # Storage provider type: "local" or "s3"
  type: "local"
  
  # S3 Storage Configuration
  s3:
    region: "us-west-2"
    bucket: "mcp-contexts"
    # Endpoint for S3-compatible services (Localstack, Minio, etc.)
    endpoint: "http://localhost:4566"
    # Force path style needed for some S3-compatible services
    force_path_style: false
    upload_part_size: 5242880  # 5MB
    download_part_size: 5242880  # 5MB
    concurrency: 5
    request_timeout: 30s
  
  # Context Storage Configuration
  context_storage:
    # Provider: "database" or "s3"
    provider: "database"
    s3_path_prefix: "contexts"

# API Server Configuration
api:
  listen_address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 90s
  base_path: "/api/v1"
  enable_cors: true
  log_requests: true
  
  # Authentication settings
  auth:
    api_keys_admin: "admin-api-key"
    api_keys_test: "test-api-key"
    jwt_secret: "test-jwt-secret"
    jwt_expiration: 24h
  
  # API rate limiting
  rate_limit:
    enabled: true
    limit: 100
    burst: 150
    expiration: 1h
  
  # Webhook configuration
  webhooks:
    github:
      enabled: true
      secret: "mock-github-secret"
      path: "/github"
    harness:
      enabled: true
      secret: "mock-harness-secret"
      path: "/harness"
    sonarqube:
      enabled: true
      secret: "mock-sonarqube-secret"
      path: "/sonarqube"
    artifactory:
      enabled: true
      secret: "mock-artifactory-secret"
      path: "/artifactory"
    xray:
      enabled: true
      secret: "mock-xray-secret"
      path: "/xray"

# Database Configuration
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "mcp"
  ssl_mode: "disable"
  dsn: "postgres://postgres:postgres@postgres:5432/mcp?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Cache Configuration
cache:
  type: "redis"
  address: "redis:6379"
  password: ""
  database: 0
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  pool_size: 10
  min_idle_conns: 2
  pool_timeout: 4

# Core Engine Configuration
engine:
  event_buffer_size: 1000
  concurrency_limit: 5
  event_timeout: 30s
  
  # GitHub Configuration
  github:
    api_token: "mock-github-token"
    webhook_secret: "mock-github-secret"
    request_timeout: 10s
    rate_limit_per_hour: 5000
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://localhost:8081/mock-github"
  
  # Harness Configuration
  harness:
    api_token: "mock-harness-token"
    account_id: "mock-harness-account"
    webhook_secret: "mock-harness-secret"
    base_url: "http://localhost:8081/mock-harness"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
  
  # SonarQube Configuration
  sonarqube:
    base_url: "http://localhost:8081/mock-sonarqube"
    token: "mock-sonarqube-token"
    webhook_secret: "mock-sonarqube-secret"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
  
  # Artifactory Configuration
  artifactory:
    base_url: "http://localhost:8081/mock-artifactory"
    username: "mock-artifactory-user"
    password: "mock-artifactory-password"
    api_key: "mock-artifactory-api-key"
    webhook_secret: "mock-artifactory-secret"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
  
  # Xray Configuration
  xray:
    base_url: "http://localhost:8081/mock-xray"
    username: "mock-xray-user"
    password: "mock-xray-password"
    api_key: "mock-xray-api-key"
    webhook_secret: "mock-xray-secret"
    request_timeout: 10s
    max_retries: 3
    retry_delay: 1s
    mock_responses: true

# Metrics Configuration
metrics:
  enabled: true
  type: "prometheus"
  endpoint: ""
  push_gateway: ""
  push_interval: 10s