# MCP Server Configuration for Local Development

# Environment (dev, staging, prod)
environment: "dev"

# Storage Configuration
storage:
  # Storage provider type: "local" or "s3"
  type: "local"
  
  # Context Storage Configuration
  context_storage:
    # Provider: "database" or "s3"
    provider: "database"

# API Server Configuration
api:
  listen_address: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 90s
  base_path: "/api/v1"
  enable_cors: true
  log_requests: true
  
  # Authentication settings
  auth:
    api_keys_admin: "admin-api-key"
    api_keys_test: "test-api-key"
    jwt_secret: "test-jwt-secret"
    jwt_expiration: 24h
  
  # API rate limiting
  rate_limit:
    enabled: false
    limit: 100
    burst: 150
    expiration: 1h
  
  # Webhook configuration
  webhooks:
    github:
      enabled: true
      secret: "mock-github-secret"
      path: "/github"

# Database Configuration
database:
  driver: "postgres"
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  database: "mcp"
  ssl_mode: "disable"
  dsn: "postgres://postgres:postgres@postgres:5432/mcp?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Cache Configuration
cache:
  type: "redis"
  address: "redis:6379"
  password: ""
  database: 0
  use_iam_auth: false
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  pool_size: 10
  min_idle_conns: 2
  pool_timeout: 4

# Core Engine Configuration
engine:
  event_buffer_size: 1000
  concurrency_limit: 5
  event_timeout: 30s
  
  # GitHub Configuration
  github:
    api_token: "mock-github-token"
    webhook_secret: "mock-github-secret"
    request_timeout: 10s
    rate_limit_per_hour: 5000
    max_retries: 3
    retry_delay: 1s
    mock_responses: true
    mock_url: "http://mockserver:8081/mock-github"

# Metrics Configuration
metrics:
  enabled: false
  type: "prometheus"
  endpoint: ""
  push_gateway: ""
  push_interval: 10s