global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Recommended security settings
# tls_config:
#   cert_file: /etc/prometheus/certs/prometheus.crt
#   key_file: /etc/prometheus/certs/prometheus.key
# 
# basic_auth:
#   username: prometheus
#   password: ${PROMETHEUS_PASSWORD}

scrape_configs:
  - job_name: 'mcp-server'
    scrape_interval: 5s
    metrics_path: '/metrics'
    scheme: 'http'  # Change to https when TLS is configured
    static_configs:
      - targets: ['mcp-server:8080']
    # Enable for authentication for metrics endpoint
    # basic_auth:
    #   username: prometheus
    #   password: ${PROMETHEUS_METRICS_PASSWORD}

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']